routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// Auth Routing
Route::group([
    'namespace'=>'Admin'
],function(){
    Auth::routes();
});



//Admin Routing
Route::group([
    'namespace' => 'Admin',
    'prefix' => '/control_panel',
    'middleware' => ['auth']
], function () {
    Route::get('/', 'HomeController@index')->name('control_panel');
    Route::get('/profile', 'ProfileController@index')->name('profile');
    Route::post('/update/profile', 'ProfileController@update')->name('update.profile');

    // Route::get('/fileManager', 'FileManagerController@index')->name('fileManager.index');
    Route::resource('/menu', 'MenuController');
    Route::post('/menu/saveMenu/', 'MenuController@saveMenu')->name('menu.saveMenu');
    Route::get('/menu/getUrl/{id}', 'MenuController@getUrl')->name('menu.getUrl');


    Route::resource('/setting','SettingController');
    Route::get('getSetting', 'SettingController@getSetting')->name('setting.getSetting');


    Route::resource('/categories', 'CategoriesController');
    Route::post('/categories/saveCategories/', 'CategoriesController@saveCategories')->name('categories.saveCategories');

    Route::resource('/contents', 'ContentsController');
    Route::get('/getDataTable', 'ContentsController@getDataTable')->name('contents.getDataTable');

    Route::resource('/gallery', 'GalleryController');
    Route::resource('/contact', 'ContactController');

});


//Web routing
Route::group([
    'namespace' => 'Web'

], function () {
    Route::group([
        'prefix' => 'category_type'
    ], function () {
        Route::get('/list/{category_type}', 'WebController@list_category_type');
        Route::get('/detail/{category_type}/{id}', 'WebController@detail_category_type')->name('detail.category_type');
    });
    Route::get('/', 'WebController@index');
    Route::get('/contact', 'WebController@contact');
    Route::get('/aboutus', 'WebController@aboutus');
     Route::post('/sendMail', 'WebController@sendMail');
     Route::get('/gallery', 'WebController@gallery');
      Route::get('/list_gallery/{id}', 'WebController@list_gallery')->name('list_gallery');
});

resources/views/admin/categories.blade.php
@extends('layouts.admin')



@section('content')
    <?php


    $id = "";

    $name = "";
    $status = "active";
    $featuredImg= "";
    $state = "Add";
    $routeAction=route('categories.store');
    $method="";
    if (isset($category_detail)) {
        $id = $category_detail['id'];

        $name = $category_detail['name'];
         $featuredImg = $category_detail['featuredImg'];
        $status = $category_detail['status'];
        $state = "Edit";
        $routeAction=route('categories.update',$id);
        $method = method_field('PUT');
    }
    ?>

    <div class="content-wrapper">
        <section class="content-header">
            <h1>
                Page Categories
            </h1>
        </section>

        <section class="content">
            <div class="box">
                <div class="box-body">
                     @include('alertMessage')

                    <div class="row">
                        <div class="col-sm-6">
                            <button class="btn btn-primary btn-sm" onclick="jstree.jstree('open_all')">Expand All</button>
                            <button class="btn btn-primary btn-sm" onclick="jstree.jstree('close_all')">Close All</button>
                            <button class="btn btn-success btn-sm" id="saveChangesBtn">Save Changes</button>
                            <a href="{{url('control_panel/categories')}}" class="btn btn-danger btn-sm"> <i
                                    class="fa fa-refresh"></i></a>
                            <hr>

                            <div class="form-group">
                                <input type="text" id="searchTree" class="form-control" placeholder="Search...">
                            </div>

                            <div id="tree"></div>
                        </div>

                        <div class="col-sm-6">
                            <h4><?= $state ?> Page Category</h4>
                            <hr>


                            <form action="<?= $routeAction ?>" method="post" enctype="multipart/form-data">

                                {{csrf_field()}}
                                {{$method}}
                                <meta name="_token" content="{!! csrf_token() !!}"/>
                                <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                                    <input type="text" name="name" value="<?= $name ?>" class="form-control"
                                           placeholder="Category Name">
                                    @if ($errors->has('name'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                    @endif
                                </div>

                                <div class="input-group">
                                <div class="form-group row">
                                    <input   class="form-control hidden " type="text" value="{{$featuredImg}}" name="oldFeaturedImg">
                                    <input type="file" name="featuredImg" class="hidden">
                                    <div class="col-md-6">
                                          <button type="button" class="btn btn-primary" id="featuredImgBtn">Select Featured Image</button>
                                    </div>
                                    <div  class="col-md-4">
                                        <img src="{{asset('files/1/thumbs/'.$featuredImg) }}" id="imgPreview" height="200px" width="200px" class="img-thumbnail hidden">
                                    </div>
                                  
                                    

                                </div>
                                </div>






                                <div class="form-group">
                                    <label for="">Status</label><br>

                                    <div class="radio-inline">
                                        <label>
                                            <input type="radio" name="status"
                                                   value="active" <?= ($status == "active") ? 'checked' : ''; ?>>
                                            Active
                                        </label>
                                    </div>
                                    <div class="radio-inline">
                                        <label>
                                            <input type="radio" name="status"
                                                   value="inactive" <?= ($status == "inactive") ? 'checked' : ''; ?>>
                                            Inactive
                                        </label>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <button class="btn btn-primary"><?= $state ?> Category</button>
                                </div>
                            </form>

                        </div>
                    </div>


                </div>
            </div>

        </section>
        <section>
            <div class="container">
                <h3 style="color:#3c8dbc">*Note:List Category name</h3>
                <ul >
                    <li>Products</li>
                    <li>Offers</li>
                    <li>Testimonials</li>
                    <li>Gallery</li>
                    <li>Events</li>
                    <li>People Reviews</li>


                </ul>
            </div>
        </section>
    </div>
    <script>
    var aspectRatioInput = 16/ 4;
    </script>
        @include('cropper')
    //jsTree
    @endsection
   
    @push('scripts')
     <link rel="stylesheet" href="{{asset('bower_components/jstree/dist/themes/default/style.min.css')}}"/>
    <script src="{{ asset('bower_components/jstree/dist/jstree.min.js')}}"></script>

    <script>
        function customMenu(node) {
            var items = {

                editItem: {
                    label: "Edit",
                    action: function () {
                        window.location.href = "{{url('control_panel/categories')}}" + "/" + node.id + "/edit";
                    }
                },
                deleteItem: {
                    label: "Delete",
                    action: function () {
                        if (node.children.length) {
                            alert('Can not delete the category which have child categories.');
                            return;
                        }
                        $.ajax({
                            url:"{{url('control_panel/categories/')}}" + "/" + node.id ,
                            type:'DELETE',
                            data:{id:node.id,_token:'{{csrf_token()}}'},
                            success:function () {
                                window.location.href = "{{url('control_panel/categories/')}}"  ;
                            },
                            error:function () {
                                alert('error');

                            }

                        });

                    }
                }
            };
            return items;
        }

        var jstree = $('#tree');
        $(function () {

            jstree.jstree({
                'plugins': ['contextmenu', 'search', 'dnd'],
                'core': {
                    'data': <?php print_r(json_encode($categories)) ?>,
                    'themes': {
                        'icons': true
                    },
                    check_callback: true
                },
                'contextmenu': {
                    'items': customMenu
                },
                "search": {
                    "case_insensitive": true,
                    "show_only_matches": true
                },

            }).on('loaded.jstree', function () {
                jstree.jstree('open_all');
            });
        });


        $("#searchTree").keyup(function () {
            var searchString = $(this).val();
            jstree.jstree('search', searchString);
        });

        var treeExport = [];
        var debunkTree = function (categories, parentID) {

            $.each(categories, function (index, data) {
                if (data.children.length) {
                    debunkTree(data.children, data.id);
                }

                treeExport.push({
                    id: data.id,
                    name: data.text,
                    parent_id: parentID,





                });
            });
        };

        $('#saveChangesBtn').on('click', function (e) {
            var categories = jstree.jstree(true).get_json('#', {flat: false});
            treeExport = [];
            debunkTree(categories, 0);
//        console.log(treeExport);

            var params={treeExport:treeExport,_token:'{{csrf_token()}}',}
            $.ajax({
                url: "{{route('categories.saveCategories')}}",
                type: 'post',
                cache: false,
                data: params,
                success: function(response) {
//                alert(response);
                    window.location.href = "{{url('control_panel/categories/')}}"  ;
                },
                error: function() {
                    alert('error');
                }
            });
        })


    </script>
 <script>
$('#featuredImgBtn').on('click',function(){
    $('input[name="featuredImg"]').click();
})

$('input[name="featuredImg"]').on('change',function() {
 


  if (this.files && this.files[0]) {
    var reader = new FileReader();

    reader.onload = function(e) {
      $('#imgPreview').attr('src', e.target.result);
    }

    reader.readAsDataURL(this.files[0]);
  }
   $('#imgPreview').removeClass('hidden');

});


    var img = "{{$featuredImg}}";
    if (img != "") {
        $('#imgPreview').removeClass('hidden');
    }
</script>
@endpush

resources/views/admin/contact.blade.php
@extends('layouts.admin')


@section('content')
<div class="content-wrapper">

    <section class="content-header">


        <h1>
          Customers Message
        </h1>
    </section>
    @include('alertMessage')


    <section class="content">
        <table class="table table-bordered" id="content_table">
            <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
               
                <th>Messages</th>
                <th>Status</th>
               
                <th >Action</th>

            </tr>
            </thead>
            <tbody>
            @isset($customer_messages)
                

                @foreach($customer_messages as $message )
                   
                <tr>
                    <td>{{$message['name']}}</td>
                    <td> {{$message['email']}}   </td>

                   
                    <td>{{str_limit($message['message'],100)}}</td>
                    <td> <form action="{{route('contact.update',$message['id'])}}" method="post">

                            <input type="hidden" value="put" name="_method">
                            {{csrf_field()}}
                            @if($message['status']=='unread' )
                            <input type="hidden" value="read" name="status">
                            <button type="submit" class="btn btn-sm btn-danger" data-toggle="tooltip" data-placement="top" title="Click For Change as Read">Unread</button>
                            @else
                            <input type="hidden" value="unread" name="status">
                            <button type="submit" class="btn btn-sm btn-success" data-toggle="tooltip" data-placement="top" title="Click For Change as Read">Read</button>
                            @endif
                        </form>


                    </td>
                   
                    <td>
                        <a  id="" c_id="{{$message['id']}}" class=" modal_msg btn btn-sm btn-info" title="Gallery"><i class="glyphicon glyphicon-eye-open"></i> </a>
                       

                        <form action="{{route('contact.destroy',$message['id'])}}" method="post">
                            <input type="hidden" value="delete" name="_method">
                            {{csrf_field()}}
                            <button type="submit" class="btn btn-sm btn-danger" data-toggle="tooltip" data-placement="top" title="Delete"><i class="glyphicon glyphicon-remove"></i></button></form>

                    </td>
                </tr>

                @endforeach
            @endisset

            </tbody>
        </table>
         <div class="modal fade" id="msgModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                                aria-hidden="true">×</span></button>
                                    <h4 class="modal-title" id="myModalLabel">Customer Message</h4>
                                </div>
                                <div class="modal-body">
                                    <p id="msg"></p>
                                </div>
                                <div class="modal-footer">

                                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

                                   
                                </div>
                            </div>
                        </div>
                    </div>
    </section>

</div>

@endsection
@push('scripts')
<script type="text/javascript">
                    $(document).ready(function(){
                        
                        $('.modal_msg').click(function(){
                     
                                 var id=$(this).attr("c_id");
                               
                    
                    var url='{{url('control_panel/contact')}}'+'/'+id;
                    // alert(url);

                    

                  $.ajax({
                                url: url,
                                type: 'get',
                                dataType: 'json',
                                     success:function($data){
                                             $('#myModalLabel').html($data['name']);
                                              $('#myModalLabel').append('<h5>('+$data['email']+')</h5>');
                                             $('#msg').html($data['message']);
                                           $('#msgModal').modal('show');
                                    },
                                error:function(data){
                                   alert('error');
                                }
              });
    });
                    });
                  
          </script>
<script>

    $('#content_table').DataTable({
        processing:true,


    });

</script>
@endpush

resources/views/admin/dashboard.blade.php
<?php if(Auth::user()->gender=='Male'){
    $defaultImg=asset('admin/images/male.jpg');
}else{
    $defaultImg=asset('admin/images/female.png');
}?>
@extends('layouts.admin')



@section('content')
<div class="content-wrapper">
    <section class="content-header">
        <h1>
            {{Auth::user()->name}}
           
            	
            
        </h1>
    </section>

    <section class="content">
        <div class="row">




                <div class="col-md-10 col-sm-12 col-xs-12 ml70">
                    <div class="info-box">
                    <span class="info-box-icon line0"><img src="{{Auth::user()->profileImg ? asset('files/1/profile/'.Auth::user()->profileImg ) : $defaultImg }}" class=""
                                                           alt="User Image"></span>

                        <div class="info-box-content">
                            <strong class="info-box-text"></strong>
                            <span class="info-box-text"><a
                                    href="{{url('control_panel/profile')}}">Profile</a></span>
                        <span class="info-box-text"> <form action="{{ route('logout') }}" method="POST">
                                {{ csrf_field() }}
                                <button type="submit" class="btn btn-default btn-flat">Sign
                                    out</button>
                            </form></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
@endsection

resources/views/admin/profile.blade.php
@extends('layouts.admin')
@section('content')
<?php

$user=Auth::user();
if($user){
$id=$user['id'];
$name=$user['name'];
$email=$user['email'];
$gender=$user['gender'];
$profileImg=$user['profileImg'];
}else{

}



    	 

?>
<div class="content-wrapper">
	<section class="content-header">
		<h1>
			Profile
		</h1>
	</section>

	<section class="content">
		<div class="row">
			<div class="col-md-offset-2 col-md-8 ">
				<div class="box">
					<div class="box-header with-border">
						<h3 class="box-title">Basic Information</h3>
					</div>	
					<div class="box-body">
					  @include('alertMessage')
						
						<form action="{{route('update.profile')}}" method="post" enctype="multipart/form-data">
						{{ csrf_field() }}
						
							<div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
								<label for="user_name">Name</label>
								<input type="text" class="form-control" id="user_name" name="name"
									   value="{{$name}}">
							</div>
							 @if ($errors->has('name'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                    @endif

							<div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
								<label for="email">Email</label>
								<input type="email" class="form-control" id="email" name="email" value="{{$email}}">
							</div>
							 @if ($errors->has('email'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                    @endif

							<div class="input-group">
								 <?php if(Auth::user()->gender=='Male'){
                               $defaultImg=asset('admin/images/male.jpg');
                               }else{
                                $defaultImg=asset('admin/images/female.png');
                              }?>

                              <div class="form-group row">
                                   <input type="hidden" name="old_profileImg" value="{{$profileImg ? $profileImg : $defaultImg }}">
                                    <input type="file" name="profileImg" class="hidden">
                                    <div class="col-md-6">
                                          <button type="button" class="btn btn-primary" id="profileImgBtn">Select Profile Image</button>
                                    </div>
                                    <div  class="col-md-4">
                                        <img src="{{$profileImg ? asset('files/1/profile/'.$profileImg ) : $defaultImg }}" id="imgPreview" height="200px" width="200px" class="img-thumbnail ">
                                    </div>
                                  
                                    

                                </div>
                               
                                     
                                    
                                 
                                 
                               
                                 	
                                  
                                </div>

                                
                                <div class="form-group{{ $errors->has('gender') ? ' has-error' : '' }}">
                              		  <label for="roles">Gender</label>


                                <div class="col-md-12">

                                    <label class="radio-inline"><input {{$gender=='Male' ? 'checked' : '' }}  type="radio" value="Male" name="gender">Male</label>

                                    <label class="radio-inline"><input type="radio" value="Female" {{$gender=='Female' ? 'checked' : '' }}  name="gender">Female</label>
                                     @if ($errors->has('gender'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('gender') }}</strong>
                                    </span>
                                    @endif


                                </div>
                                
                            </div>
                            

                               
                                
                          
                            	<h4  style="margin-top:50px;" class="text-info">*Only if you want to change the password.*</h4>
                            	
							

							<div class="form-group {{ Session::get('incorrect') ? 'has-error' : ''}}">
								<label for="current_password">Current Password</label>
								<input type="password" class="form-control" id="current_password"
									   name="current_password">
									   @if (Session::get('incorrect'))
                                        <span class="help-block">
                                        <strong>{{Session::get('incorrect') }}</strong>
                                    </span>
                                    @endif
							</div>
							<div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
								<label for="password">New Password
									<small></small>
								</label>
								<input type="password" class="form-control" id="password"
									   name="password">
									    @if ($errors->has('password'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                    @endif
							</div>
							<div class="form-group{{ $errors->has('password_confirmation') ? ' has-error' : '' }}">
								<label for="password-confirm">Confirm Password
									<small></small>
								</label>
								<input type="password" class="form-control" id="password_confirmation"
									   name="password_confirmation">
									    @if ($errors->has('password_confirmation'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('password_confirmation') }}</strong>
                                    </span>
                                    @endif
							</div>

							

							<div class="form-group">
								<button class="btn btn-primary mr15" type="submit">Save Changes</button>
								<button class="btn btn-danger" type="button" id="cancelBtn"
										onclick="window.history.back()">Cancel
								</button>
							</div>

						</form>
					</div>
				</div>
			</div>
		</div>
	</section>
</div>




@endsection

@push('scripts')
<script>
$('#profileImgBtn').on('click',function(){
    $('input[name="profileImg"]').click();
})

$('input[name="profileImg"]').on('change',function() {
 


  if (this.files && this.files[0]) {
    var reader = new FileReader();

    reader.onload = function(e) {
      $('#imgPreview').attr('src', e.target.result);
    }

    reader.readAsDataURL(this.files[0]);
  }
   $('#imgPreview').removeClass('hidden');

});


    var img = "{{$profileImg}}";
    if (img != "") {
        $('#imgPreview').removeClass('hidden');
    }
</script>



@endpush