routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// Auth Routing
Route::group([
    'namespace'=>'Admin'
],function(){
    Auth::routes();
});



//Admin Routing
Route::group([
    'namespace' => 'Admin',
    'prefix' => '/control_panel',
    'middleware' => ['auth']
], function () {
    Route::get('/', 'HomeController@index')->name('control_panel');
    Route::get('/profile', 'ProfileController@index')->name('profile');
    Route::post('/update/profile', 'ProfileController@update')->name('update.profile');

    // Route::get('/fileManager', 'FileManagerController@index')->name('fileManager.index');
    Route::resource('/menu', 'MenuController');
    Route::post('/menu/saveMenu/', 'MenuController@saveMenu')->name('menu.saveMenu');
    Route::get('/menu/getUrl/{id}', 'MenuController@getUrl')->name('menu.getUrl');


    Route::resource('/setting','SettingController');
    Route::get('getSetting', 'SettingController@getSetting')->name('setting.getSetting');


    Route::resource('/categories', 'CategoriesController');
    Route::post('/categories/saveCategories/', 'CategoriesController@saveCategories')->name('categories.saveCategories');

    Route::resource('/contents', 'ContentsController');
    Route::get('/getDataTable', 'ContentsController@getDataTable')->name('contents.getDataTable');

    Route::resource('/gallery', 'GalleryController');
    Route::resource('/contact', 'ContactController');

});


//Web routing
Route::group([
    'namespace' => 'Web'

], function () {
    Route::group([
        'prefix' => 'category_type'
    ], function () {
        Route::get('/list/{category_type}', 'WebController@list_category_type');
        Route::get('/detail/{category_type}/{id}', 'WebController@detail_category_type')->name('detail.category_type');
    });
    Route::get('/', 'WebController@index');
    Route::get('/contact', 'WebController@contact');
    Route::get('/aboutus', 'WebController@aboutus');
     Route::post('/sendMail', 'WebController@sendMail');
     Route::get('/gallery', 'WebController@gallery');
      Route::get('/list_gallery/{id}', 'WebController@list_gallery')->name('list_gallery');
});

app/Http/Controllers/Admin/GalleryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Model\Admin\ContentsModel;
use Faker\Provider\DateTime;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\Admin\GalleryModel;
use Image;
use DB;
use Validator;
use Illuminate\Support\Facades\Session;
use File;

class GalleryController extends Controller
{
    private $data;
    public function __construct()
    {
        $this->data['getSetting']=SettingController::getSetting();
         $this->data['title']='Gallery';



    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $formInput=$request->all();
        $formInput['created_at']=new \DateTime();
        $isValid=Validator::make($request->all(), [
            'images' => 'required|',

        ]);
        if ($isValid->fails()) {
            return redirect('control_panel/gallery/'.$formInput['contentId'])
                ->withErrors($isValid)
                ->withInput();
        }

        $contentImages=$request->file();
        if(isset($contentImages['images'])){
            foreach ($contentImages['images'] as $image){

                $formInput['images']=$this->uploadImage($image);

                GalleryModel::insert($formInput);
            }
            Session::flash('success', 'Uploaded Successfully');
            return redirect('control_panel/gallery/'.$formInput['contentId']);

        }










    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $this->data['contentDetails']=ContentsModel::find($id);
        $this->data['images']=GalleryModel::where('contentId',$id)->paginate(4);

        return view('admin/gallery/list',$this->data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $contentDetails=GalleryModel::find($id);
        $contentId=$contentDetails['contentId'];
        $image=$contentDetails['images'];
        $file_path=public_path($image);

        if (GalleryModel::find($id)->delete()) {
            if(file_exists($file_path)){
                @unlink($file_path);
            }
            Session::flash('success', 'Delete contents Successfully');


        } else {
            Session::flash('error', 'Cannot Delete Image ');
        }
        return redirect()->route('gallery.show',$contentId);
    }
    public function uploadImage($contentImage)
    {
        $path=public_path('files/1/Gallery/Content/');
        if (!file_exists($path)) {
        $result = File::makeDirectory($path, 0775, true);
        }
        $filename =$contentImage->getClientOriginalName();

        Image::make($contentImage)->resize(300, 300)->save('files/1/Gallery/Content/'.$filename);
        return ('files/1/Gallery/Content/'.$filename);

    }
}

resources/views/admin/gallery/list.blade.php
@extends('layouts.admin')
@section('content')

    <div class="content-wrapper" xmlns="http://www.w3.org/1999/html">
        <section class="content-header">
            <button type="button" class="btn btn-info pull-right" data-toggle="collapse" data-target="#gallery"><i
                        class="fa fa-plus"></i> Add Gallery
            </button>
            <h1>
               <a href="{{route('contents.index')}}">Contents</a><span>|Gallery( {{$contentDetails['name']}})
            </h1>
        </section>

        <section class="content">
           @include('alertMessage')
                @if ($errors->has('images'))
                    <div id="msg-alert" class="alert alert-danger">
                        <strong>{{ $errors->first('images') }}</strong>
                    </div>
                @endif

            <div class="row">


                <div class="col-md-12" >
                    <div class="box">
                        <div class="box-body">
                            
                            <form id="gallery" class="collapse collapse-class" action="{{route('gallery.store')}}" method="post" enctype="multipart/form-data">
                                {{csrf_field()}}


                                <input type="hidden" name="contentId" value="{{$contentDetails['id']}}">
                                <div class="form-group">
                                    <label class="control-label">Select File</label>
                                    <input id="input-2" name="images[]" type="file" class="file" multiple
                                           data-show-upload="false" data-show-caption="true">
                                </div>


                                <div class="form-group">
                                    <button class="btn btn-primary mr15" type="submit"
                                            id="submitFormBtn">Upload
                                    </button>
                                    <button class="btn btn-danger" type="button" id="cancelBtn"
                                            onclick="window.history.back()">Cancel
                                    </button>
                                </div>
                            </form>
                            <div class="row">
                                @isset($images)
                                   
                                    @foreach($images as $image)
                                        <div class="col-md-3">
                                            <img width="200" height="200" src="{{asset($image['images'])}}"/>

                                            <form action="{{route('gallery.destroy',$image['id'])}}"
                                                  method="post">
                                                <input type="hidden" value="delete" name="_method">
                                                <input type="hidden" value="{{$image['contentId']}}"
                                                       name="contentId">
                                                <input type="hidden" value="{{csrf_token()}}" name="_token">
                                                <button type="submit" class="label label-danger ">Remove</button>
                                            </form>
                                        </div>






                                    @endforeach
                                @endisset
                            </div>
                            <div class="pagination-area">
                                <ul class="pagination">
                                    <li>{{ $images->links() }}</li>
                                    
                                </ul>

                                

                                <span>Page 1 of 4</span>
                            </div><!--Pagination-->
                        </div>
                    </div>
                </div>

            </div>


        </section>

    </div>
@endsection