routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// Auth Routing
Route::group([
    'namespace'=>'Admin'
],function(){
    Auth::routes();
});



//Admin Routing
Route::group([
    'namespace' => 'Admin',
    'prefix' => '/control_panel',
    'middleware' => ['auth']
], function () {
    Route::get('/', 'HomeController@index')->name('control_panel');
    Route::get('/profile', 'ProfileController@index')->name('profile');
    Route::post('/update/profile', 'ProfileController@update')->name('update.profile');

    // Route::get('/fileManager', 'FileManagerController@index')->name('fileManager.index');
    Route::resource('/menu', 'MenuController');
    Route::post('/menu/saveMenu/', 'MenuController@saveMenu')->name('menu.saveMenu');
    Route::get('/menu/getUrl/{id}', 'MenuController@getUrl')->name('menu.getUrl');


    Route::resource('/setting','SettingController');
    Route::get('getSetting', 'SettingController@getSetting')->name('setting.getSetting');


    Route::resource('/categories', 'CategoriesController');
    Route::post('/categories/saveCategories/', 'CategoriesController@saveCategories')->name('categories.saveCategories');

    Route::resource('/contents', 'ContentsController');
    Route::get('/getDataTable', 'ContentsController@getDataTable')->name('contents.getDataTable');

    Route::resource('/gallery', 'GalleryController');
    Route::resource('/contact', 'ContactController');

});


//Web routing
Route::group([
    'namespace' => 'Web'

], function () {
    Route::group([
        'prefix' => 'category_type'
    ], function () {
        Route::get('/list/{category_type}', 'WebController@list_category_type');
        Route::get('/detail/{category_type}/{id}', 'WebController@detail_category_type')->name('detail.category_type');
    });
    Route::get('/', 'WebController@index');
    Route::get('/contact', 'WebController@contact');
    Route::get('/aboutus', 'WebController@aboutus');
     Route::post('/sendMail', 'WebController@sendMail');
     Route::get('/gallery', 'WebController@gallery');
      Route::get('/list_gallery/{id}', 'WebController@list_gallery')->name('list_gallery');
});

app/Http/Controllers/Admin/ContentsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\ContentRequest;
use App\Model\Admin\Categories;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\Admin\ContentsModel;
use App\Http\Controllers\Admin\SettingController;
use DB;
use Validator;
use Illuminate\Support\Facades\Session;
use Yajra\Datatables\Datatables;
use Image;

class ContentsController extends Controller
{

    private $data;
    public function __construct()
    {
        $this->data['getSetting']=SettingController::getSetting();
        $this->data['categories']=Categories::select('name','id','status')->where(['status' => 'active'])->get() ;
         $this->data['title']='Contents';


    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->data['listContents']=ContentsModel::get();

        return view('admin/contents/list',$this->data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {



        return view('admin/contents/form',$this->data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ContentRequest $request)
    {
        $formInput = $request->all();
       if($this->countSlider($formInput['slider'])==false) {
        Session::flash('errorSlider', '*FeaturedImg couldnot be more than 5*');
         return redirect()->back();
       }
       
        $formInput['featuredImg']=$this->imgUpload($request->file('featuredImg'));
       
        $formInput['created_at']=new \DateTime();
       

        unset($formInput['oldFeaturedImg']);




        if (ContentsModel::insert($formInput)) {
            Session::flash('success', 'Add Data Successfully');
            return redirect('control_panel/contents');


        } else {
            Session::flash('error', 'Erro to Add Data ');

        }
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $this->data['contents'] = ContentsModel::find($id);
        return view("admin/contents/form", $this->data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $formData = $request->all();
        $image_name=$formData['oldFeaturedImg'];
        if($this->countSlider($formData['slider'])==false) {
        Session::flash('errorSlider', '*FeaturedImg couldnot be more than 5*');
         return redirect()->back();
       }


        if (empty($request->file('featuredImg'))) {

            $formData['featuredImg'] = $formData['oldFeaturedImg'];
        }else{
             $formData['featuredImg']=$this->imgUpload($request->file('featuredImg'));
            if($image_name){
                    $this->deleteImg($image_name);
                }
        }

        unset($formData['oldFeaturedImg']);
        if (ContentsModel::find($id)->update($formData)) {
            
            Session::flash('success', 'Update contents Successfully');
            return redirect()->route('contents.index');

        } else {
            Session::flash('error', 'Cannot Updated contents Successfully');
            return redirect()->route('contents.edit', $id);

        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $image_name=ContentsModel::select('featuredImg')->where('id',$id)->first();
        

        if (ContentsModel::find($id)->delete()) {
            if($image_name){

             $this->deleteImg($image_name['featuredImg']);
            }
            Session::flash('success', 'Delete contents Successfully');


        } else {
            Session::flash('error', 'Cannot Delete contents Successfully');
        }
        return redirect()->route('contents.index');
    }
    public function countSlider($slider){
        if($slider=='no'){
             return true;
        }
        $countSlider=count(ContentsModel::where('slider','yes')->get());
        if($countSlider>=5){
              return false;

        }else{
            return true;
        }
    }

public function imgUpload($image){
         if($image){
                $image_name= time().'.png';
                 $path = public_path() . "/files/1/" . $image_name;
                Image::make($image)->resize(1366,768)->save($path);
                $path2 = public_path() . "/files/1/thumbs/" . $image_name;
                Image::make($image)->resize(200,200)->save($path2);
                return $image_name;


      
       

       }
}
public function deleteImg($image_name){
             $pathImg1=public_path('files/1/'.$image_name);
             if(file_exists($pathImg1) ){
                 @unlink($pathImg1);
             }
              $pathImg2=public_path('files/1/thumbs/'.$image_name);
           
             if(file_exists($pathImg2) ){
                 @unlink($pathImg2);
             }
             return true;
}

}

resources/views/admin/contents/form.blade.php
@extends('layouts.admin')


@section('content')
    <?php
    $id = "";
    $name = old('name');
    $featuredImg = "";
    $description =  old('description');
    $categoryId = old('categoryId');
    $slider="no";

    $is_deletable = "yes";
    $status = 'active';
    $state = 'Add';
    $routeAction=route('contents.store');
    $method = "";
    if (isset($contents)) {
        $id = $contents['id'];
        $name = $contents['name'];
        $featuredImg = $contents['featuredImg'];
        $description = $contents['description'];
        $categoryId = $contents['categoryId'];
        $is_deletable = $contents['is_deletable'];
        $slider = $contents['slider'];
        $status = $contents['status'];
        $state = 'Edit';
        $routeAction=route('contents.update',$id);
        $method = method_field('PUT');




    }


    ?>
    <div class="content-wrapper">
        <section class="content-header">
            <h1>
                <a href="{{route('contents.index')}}">Contents</a><span>|</span><?= $state ?> Web Content
            </h1>
        </section>

        <section class="content">
             @include('alertMessage')
            <div class="row">
                <div class="col-md-12">
                    <div class="box">
                        <div class="box-body">



                            <form action="{{$routeAction}}" method="post"  enctype="multipart/form-data">
                                {{csrf_field()}}
                                {{$method}}
                                <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                                    <label for="name">Content Name</label>
                                    <input type="text" class="form-control" id="name" name="name" value="<?php echo $name ?>">
                                    @if ($errors->has('name'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                    @endif
                                </div>


                                <div class="form-group{{ $errors->has('categoryId') ? ' has-error' : '' }}">
                                    <label for="categoryId">Category</label>
                                    <select name="categoryId" id="categoryId" class="chosen-select form-control"
                                            data-placeholder="Select Category" >
                                        <option  value="" disabled selected>Select Categories</option>
                                        @foreach($categories as $category)
                                            <option
                                                    value="{{$category['id'] }}" {{($category['id'] == $categoryId) ? "selected" : "" }}  >{{$category['name']}}</option>
                                            @endforeach


                                    </select>
                                    @if ($errors->has('categoryId'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('categoryId') }}</strong>
                                        </span>
                                    @endif
                                </div>

                                <div class="form-group row">
                                    <input   class="form-control hidden " type="text" value="{{$featuredImg}}" name="oldFeaturedImg">
                                    <input type="file" name="featuredImg" class="hidden">
                                    <div class="col-md-4">
                                          <button type="button" class="btn btn-primary" id="featuredImgBtn">Select Featured Image</button>
                                    </div>
                                    <div  class="col-md-4">
                                        <img src="{{asset('files/1/thumbs/'.$featuredImg) }}" id="imgPreview" height="200px" width="200px" class="img-thumbnail hidden">
                                    </div>
                                  
                                    

                                </div>

                                

                                <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                                    <label for="description">Description</label>
                                    <textarea id="description_textarea" name="description" id="description"
                                             ><?php echo $description ?></textarea>
                                    @if ($errors->has('description'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('description') }}</strong>
                                        </span>
                                    @endif
                                </div>


                                <div class="form-group">
                                    <label for="">Deletable</label><br>

                                    <div class="radio-inline">
                                        <label>
                                            <input type="radio" name="is_deletable"
                                                   value="yes" <?php echo ($is_deletable == "yes") ? 'checked' : ''; ?>> Yes
                                        </label>
                                    </div>
                                    <div class="radio-inline">
                                        <label>
                                            <input type="radio" name="is_deletable"
                                                   value="no" <?php echo ($is_deletable == "no") ? 'checked' : ''; ?>>
                                            No
                                        </label>
                                    </div>
                                </div>
                                <div class=" form-group{{ Session::get('errorSlider') ? ' has-error' : '' }}">
                                    <label for="">Slider</label><br>

                                    <div class="radio-inline">
                                        <label>
                                            <input type="radio" name="slider"
                                                   value="yes" <?php echo ($slider == "yes") ? 'checked' : ''; ?>> Yes
                                        </label>
                                    </div>
                                    <div class="radio-inline">
                                        <label>
                                            <input type="radio" name="slider"
                                                   value="no" <?php echo ($slider == "no") ? 'checked' : ''; ?>>
                                            No
                                        </label>
                                    </div>
                                     @if (Session::get('errorSlider'))
                                        <span class="help-block">
                                        <strong>{{Session::get('errorSlider')}}</strong>
                                        </span>
                                    @endif
                                </div>


                                <div class="form-group">
                                    <label for="">Status</label><br>

                                    <div class="radio-inline">
                                        <label>
                                            <input type="radio" name="status"
                                                   value="active" {{($status == "active") ? 'checked' : ''}} > Active
                                        </label>
                                    </div>
                                    <div class="radio-inline">
                                        <label>
                                            <input type="radio" name="status"
                                                   value="inactive" {{ ($status == "inactive") ? 'checked' : ''}}>
                                            Inactive
                                        </label>
                                    </div>
                                </div>

                                <input type="hidden" id="id" name="id" value="{{$id }}">

                                <div class="form-group">
                                    <button class="btn btn-primary mr15" type="submit"
                                            id="submitFormBtn">{{$state}} </button>
                                    <button class="btn btn-danger" type="button" id="cancelBtn"
                                            onclick="window.history.back()">Cancel
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </section>
    </div>


@endsection


@push('scripts')


<script src="{{asset('/vendor/unisharp/laravel-ckeditor/ckeditor.js')}}"></script>
<script src="{{asset('/vendor/unisharp/laravel-ckeditor/adapters/jquery.js')}}"></script>
<script>
    var aspectRatioInput =16/9;
</script>
<script>
    $(function() {
    $('#description_textarea').ckeditor({
        toolbar: 'Full',
        enterMode : CKEDITOR.ENTER_BR,
        shiftEnterMode: CKEDITOR.ENTER_P
    });
});
</script>

<script>
$('#featuredImgBtn').on('click',function(){
    $('input[name="featuredImg"]').click();
})

$('input[name="featuredImg"]').on('change',function() {
 


  if (this.files && this.files[0]) {
    var reader = new FileReader();

    reader.onload = function(e) {
      $('#imgPreview').attr('src', e.target.result);
    }

    reader.readAsDataURL(this.files[0]);
  }
   $('#imgPreview').removeClass('hidden');

});


    var img = "{{$featuredImg}}";
    if (img != "") {
        $('#imgPreview').removeClass('hidden');
    }
</script>

@endpush

resources/views/admin/contents/list.blade.php
@extends('layouts.admin')


@section('content')
<div class="content-wrapper">

    <section class="content-header">

        <a href="{{route('contents.create')}}" class="btn btn-primary pull-right"><i
                    class="fa fa-plus"></i>Add
            Web Content</a>
        <h1>
            Page Content
        </h1>
    </section>
    @include('alertMessage')


    <section class="content">
        <table class="table table-bordered" id="content_table">
            <thead>
            <tr>
                <th>Name</th>
                <th>Category</th>
                <th>Featured Image</th>
                <th>Descriptions</th>
                <th>Created At</th>
                <th>Updated At</th>
                <th >Action</th>

            </tr>
            </thead>
            <tbody>
            @if(empty($listContents))
                <h1>No Lists Of Content Data</h1>
            @else

                @foreach($listContents as $content )
                    <?php  $category=App\Model\Admin\ContentsModel::find($content['id'])?>
                <tr>
                    <td>{{$content['name']}}</td>
                    <td>{{$category->category()->first()->name}}</td>

                    <td><img src="{{asset('files/1/thumbs/'.$content['featuredImg'])}}" height="50px" width="50px"></td>
                    <td>{{str_limit($content['description'],100)}}</td>
                    <td>{{$content['created_at']}}</td>
                    <td>{{$content['updated_at']}}</td>
                    <td>
                        <a href="{{route('gallery.show',$content['id'])}}" class="btn btn-sm btn-info" data-toggle="tooltip" data-placement="top" title="Gallery"><i class="glyphicon glyphicon-picture"></i> </a>
                        <a href="{{route('contents.edit',$content['id'])}}" class="btn btn-sm btn-primary" data-toggle="tooltip" data-placement="top" title="Edit"><i class="glyphicon glyphicon-edit"></i> </a>

                        <form action="{{route('contents.destroy',$content['id'])}}" method="post">
                            <input type="hidden" value="delete" name="_method">
                            {{csrf_field()}}
                            <button type="submit" class="btn btn-sm btn-danger delBtn" data-toggle="tooltip" data-placement="top" title="Delete"><i class="glyphicon glyphicon-remove"></i></button></form>

                    </td>
                </tr>

                @endforeach
            @endif

            </tbody>
        </table>
    </section>

</div>

@endsection
@push('scripts')
<script>

    $('#content_table').DataTable({
        processing:true,


    });
    $('.delBtn').on('click',function(){
        if(confirm('Are you sure want to delete ?')==false){
            return false;
        }
    })

</script>
@endpush